name: Test and release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - "master"

jobs:
  shared:
    uses: https://github.com/Shanridhu/github-action-maven-example-start/blob/.github/workflows/main.yml@master
    with:
      enable-code-scans: true
    secrets:
      ghcr-token: ${{ secrets.shared_secret }} 
